/**
 * lib/menu-items.ts
 * Full 2026 McDonald's menu — bilingual assembly sequences for the build-order game.
 * Each item's steps are in the CORRECT order; the game shuffles and asks the user to restore them.
 */

export type MenuCategory = "breakfast" | "burgers" | "chicken" | "mccafe" | "beverages" | "sides";

export interface MenuItem {
  id: string;
  name: string;       // EN display name
  nameEs: string;     // ES display name
  category: MenuCategory;
  emoji: string;
  steps: string[];    // EN assembly steps in correct order
  stepsEs: string[];  // ES assembly steps in correct order
  tipEn: string;
  tipEs: string;
}

export const CATEGORY_META: Record<MenuCategory, { emoji: string; labelEs: string; labelEn: string }> = {
  breakfast:  { emoji: "🥞", labelEs: "Desayuno",         labelEn: "Breakfast" },
  burgers:    { emoji: "🍔", labelEs: "Burgers",           labelEn: "Burgers" },
  chicken:    { emoji: "🍗", labelEs: "Pollo & Pescado",   labelEn: "Chicken & Fish" },
  mccafe:     { emoji: "☕", labelEs: "McCafé",            labelEn: "McCafé" },
  beverages:  { emoji: "🥤", labelEs: "Bebidas",           labelEn: "Beverages" },
  sides:      { emoji: "🍟", labelEs: "Acompañamientos",   labelEn: "Sides" },
};

export const MENU_ITEMS: MenuItem[] = [

  // ─── BREAKFAST ──────────────────────────────────────────────────────────────

  {
    id: "egg-mcmuffin",
    name: "Egg McMuffin",
    nameEs: "Egg McMuffin",
    category: "breakfast",
    emoji: "🫓",
    steps: [
      "Toast English Muffin — butter both halves",
      "Place heel (bottom half) on wrapper",
      "Add Cheddar cheese slice to heel",
      "Add Canadian Bacon on cheese",
      "Add round egg on Canadian Bacon",
      "Close with crown (top half)",
    ],
    stepsEs: [
      "Tostar el English Muffin — mantequilla en ambas mitades",
      "Colocar el heel (mitad inferior) en el wrapper",
      "Agregar rebanada de queso Cheddar al heel",
      "Agregar Canadian Bacon sobre el queso",
      "Agregar huevo redondo sobre el Canadian Bacon",
      "Cerrar con el crown (mitad superior)",
    ],
    tipEn: "Order: cheese → Canadian Bacon → egg. Never swap bacon and egg.",
    tipEs: "Orden: queso → Canadian Bacon → huevo. Nunca intercambiar tocino y huevo.",
  },

  {
    id: "sausage-mcmuffin",
    name: "Sausage McMuffin",
    nameEs: "Sausage McMuffin",
    category: "breakfast",
    emoji: "🫓",
    steps: [
      "Toast English Muffin — butter both halves",
      "Place heel on wrapper",
      "Add Cheddar cheese to heel",
      "Add sausage patty on cheese",
      "Close with crown",
    ],
    stepsEs: [
      "Tostar el English Muffin — mantequilla en ambas mitades",
      "Colocar el heel en el wrapper",
      "Agregar queso Cheddar al heel",
      "Agregar patty de salchicha sobre el queso",
      "Cerrar con el crown",
    ],
    tipEn: "Cheese always touches the heel; sausage sits directly on cheese.",
    tipEs: "El queso siempre toca el heel; la salchicha va directamente sobre el queso.",
  },

  {
    id: "sausage-egg-mcmuffin",
    name: "Sausage McMuffin with Egg",
    nameEs: "Sausage McMuffin con Huevo",
    category: "breakfast",
    emoji: "🫓",
    steps: [
      "Toast English Muffin — butter both halves",
      "Place heel on wrapper",
      "Add Cheddar cheese to heel",
      "Add sausage patty on cheese",
      "Add round egg on top of sausage",
      "Close with crown",
    ],
    stepsEs: [
      "Tostar el English Muffin — mantequilla en ambas mitades",
      "Colocar el heel en el wrapper",
      "Agregar queso Cheddar al heel",
      "Agregar patty de salchicha sobre el queso",
      "Agregar huevo redondo encima de la salchicha",
      "Cerrar con el crown",
    ],
    tipEn: "Egg goes ABOVE sausage — never between cheese and sausage.",
    tipEs: "El huevo va ENCIMA de la salchicha — nunca entre el queso y la salchicha.",
  },

  {
    id: "bacon-egg-cheese-mcmuffin",
    name: "Bacon, Egg & Cheese McMuffin",
    nameEs: "McMuffin Tocino, Huevo y Queso",
    category: "breakfast",
    emoji: "🫓",
    steps: [
      "Toast English Muffin — butter both halves",
      "Place heel on wrapper",
      "Add Cheddar cheese to heel",
      "Add bacon strips (folded to fit)",
      "Add round egg on bacon",
      "Close with crown",
    ],
    stepsEs: [
      "Tostar el English Muffin — mantequilla en ambas mitades",
      "Colocar el heel en el wrapper",
      "Agregar queso Cheddar al heel",
      "Agregar tiras de tocino (dobladas para ajustar)",
      "Agregar huevo redondo sobre el tocino",
      "Cerrar con el crown",
    ],
    tipEn: "Bacon folds to stay inside the muffin — egg always on top.",
    tipEs: "El tocino se dobla para quedar dentro del muffin — el huevo siempre encima.",
  },

  {
    id: "sausage-mcgriddles",
    name: "Sausage McGriddles",
    nameEs: "Sausage McGriddles",
    category: "breakfast",
    emoji: "🧇",
    steps: [
      "Place griddle cake heel on wrapper",
      "Add Cheddar cheese slice",
      "Add sausage patty on cheese",
      "Place griddle cake crown on top",
    ],
    stepsEs: [
      "Colocar la tortita de griddle (heel) en el wrapper",
      "Agregar rebanada de queso Cheddar",
      "Agregar patty de salchicha sobre el queso",
      "Colocar la tortita de griddle (crown) encima",
    ],
    tipEn: "McGriddles have maple syrup baked in — do NOT add extra syrup.",
    tipEs: "Los McGriddles tienen jarabe de maple incorporado — NO agregar jarabe extra.",
  },

  {
    id: "bacon-egg-cheese-mcgriddles",
    name: "Bacon, Egg & Cheese McGriddles",
    nameEs: "McGriddles Tocino, Huevo y Queso",
    category: "breakfast",
    emoji: "🧇",
    steps: [
      "Place griddle cake heel on wrapper",
      "Add Cheddar cheese",
      "Add bacon strips on cheese",
      "Add folded egg on bacon",
      "Place griddle cake crown on top",
    ],
    stepsEs: [
      "Colocar la tortita de griddle (heel) en el wrapper",
      "Agregar queso Cheddar",
      "Agregar tiras de tocino sobre el queso",
      "Agregar huevo doblado sobre el tocino",
      "Colocar la tortita de griddle (crown) encima",
    ],
    tipEn: "Layer sequence: cheese → bacon → egg. Always.",
    tipEs: "Secuencia de capas: queso → tocino → huevo. Siempre.",
  },

  {
    id: "sausage-biscuit",
    name: "Sausage Biscuit",
    nameEs: "Biscuit de Salchicha",
    category: "breakfast",
    emoji: "🥐",
    steps: [
      "Butter biscuit on both halves",
      "Place biscuit heel on wrapper",
      "Add sausage patty",
      "Close with biscuit crown",
    ],
    stepsEs: [
      "Untar mantequilla en ambas mitades del biscuit",
      "Colocar el heel del biscuit en el wrapper",
      "Agregar patty de salchicha",
      "Cerrar con el crown del biscuit",
    ],
    tipEn: "Biscuit is buttered on BOTH halves — skip one and it's wrong.",
    tipEs: "El biscuit se unta en AMBAS mitades — omitir una es incorrecto.",
  },

  {
    id: "bacon-egg-cheese-biscuit",
    name: "Bacon, Egg & Cheese Biscuit",
    nameEs: "Biscuit Tocino, Huevo y Queso",
    category: "breakfast",
    emoji: "🥐",
    steps: [
      "Butter biscuit on both halves",
      "Place biscuit heel on wrapper",
      "Add Cheddar cheese",
      "Add bacon strips on cheese",
      "Add folded egg on bacon",
      "Close with biscuit crown",
    ],
    stepsEs: [
      "Untar mantequilla en ambas mitades del biscuit",
      "Colocar el heel del biscuit en el wrapper",
      "Agregar queso Cheddar",
      "Agregar tiras de tocino sobre el queso",
      "Agregar huevo doblado sobre el tocino",
      "Cerrar con el crown del biscuit",
    ],
    tipEn: "Same layer order as McGriddles: cheese → bacon → egg.",
    tipEs: "Mismo orden que McGriddles: queso → tocino → huevo.",
  },

  {
    id: "hash-browns",
    name: "Hash Browns",
    nameEs: "Hash Browns",
    category: "breakfast",
    emoji: "🟫",
    steps: [
      "Drop frozen hash brown in oil at 335°F / 168°C",
      "Fry 2:45 – 3:00 min until golden brown",
      "Lift basket and drain oil for 10 seconds",
      "Salt immediately while still hot",
      "Sleeve and serve — max hold 7 min",
    ],
    stepsEs: [
      "Sumergir hash brown congelado en aceite a 335°F / 168°C",
      "Freír 2:45 – 3:00 min hasta dorar",
      "Levantar canasta y drenar aceite por 10 segundos",
      "Salar inmediatamente mientras está caliente",
      "Empacar en sleeve y servir — hold máximo 7 min",
    ],
    tipEn: "Salt AFTER draining — never over the fryer. Hold ≤ 7 min.",
    tipEs: "Salar DESPUÉS de drenar — nunca sobre la freidora. Hold ≤ 7 min.",
  },

  {
    id: "hotcakes",
    name: "Hotcakes",
    nameEs: "Hotcakes",
    category: "breakfast",
    emoji: "🥞",
    steps: [
      "Ladle batter onto griddle — 3 portions",
      "Cook until bubbles form and edges set (~2 min)",
      "Flip each hotcake once",
      "Cook second side until golden (~1:30 min)",
      "Stack 3 hotcakes on tray",
      "Serve with butter cups and syrup packet",
    ],
    stepsEs: [
      "Verter la mezcla en el griddle — 3 porciones",
      "Cocinar hasta que se formen burbujas y los bordes cuajen (~2 min)",
      "Voltear cada hotcake una sola vez",
      "Cocinar el segundo lado hasta dorar (~1:30 min)",
      "Apilar 3 hotcakes en la bandeja",
      "Servir con mantequilla y paquete de jarabe",
    ],
    tipEn: "Flip only ONCE — multiple flips make hotcakes dense.",
    tipEs: "Voltear solo UNA VEZ — voltear varias veces los hace densos.",
  },

  {
    id: "hotcakes-sausage",
    name: "Hotcakes & Sausage",
    nameEs: "Hotcakes con Salchicha",
    category: "breakfast",
    emoji: "🥞",
    steps: [
      "Start sausage patty on griddle first (it takes longer)",
      "Ladle hotcake batter — 3 portions",
      "Cook and flip sausage; cook and flip hotcakes",
      "Stack 3 hotcakes on tray",
      "Place sausage patty alongside hotcakes",
      "Add butter cups and syrup packet",
    ],
    stepsEs: [
      "Empezar el patty de salchicha en el griddle primero (tarda más)",
      "Verter mezcla de hotcakes — 3 porciones",
      "Cocinar y voltear la salchicha; cocinar y voltear los hotcakes",
      "Apilar 3 hotcakes en la bandeja",
      "Colocar el patty de salchicha junto a los hotcakes",
      "Agregar mantequilla y paquete de jarabe",
    ],
    tipEn: "Sausage starts FIRST — timing them to finish together is the skill.",
    tipEs: "La salchicha empieza PRIMERO — sincronizar que terminen juntos es la habilidad.",
  },

  {
    id: "oatmeal",
    name: "Fruit & Maple Oatmeal",
    nameEs: "Avena con Fruta y Maple",
    category: "breakfast",
    emoji: "🥣",
    steps: [
      "Pour hot water into oatmeal cup and stir",
      "Let stand 60 seconds to fully thicken",
      "Add diced apple pieces",
      "Add dried cranberry & raisin blend",
      "Drizzle maple-flavored syrup",
      "Place lid on cup",
    ],
    stepsEs: [
      "Verter agua caliente en la taza de avena y mezclar",
      "Dejar reposar 60 segundos para espesar completamente",
      "Agregar trozos de manzana picada",
      "Agregar mezcla de arándanos secos y pasas",
      "Rociar jarabe con sabor a maple",
      "Colocar la tapa en la taza",
    ],
    tipEn: "Full 60-second rest is mandatory — undercooked oats are gummy.",
    tipEs: "Los 60 segundos completos de reposo son obligatorios — la avena cruda queda gomosa.",
  },

  // ─── BURGERS ────────────────────────────────────────────────────────────────

  {
    id: "hamburger",
    name: "Hamburger",
    nameEs: "Hamburguesa",
    category: "burgers",
    emoji: "🍔",
    steps: [
      "Place heel (bottom bun) on wrapper",
      "Apply ketchup (1/3 oz)",
      "Apply mustard (1/10 oz)",
      "Add 1 pickle slice",
      "Add dehydrated onions (1/4 oz)",
      "Place 10:1 beef patty",
      "Close with crown (top bun)",
    ],
    stepsEs: [
      "Colocar el heel (pan inferior) en el wrapper",
      "Aplicar catsup (1/3 oz)",
      "Aplicar mostaza (1/10 oz)",
      "Agregar 1 rebanada de pepinillo",
      "Agregar cebolla deshidratada (1/4 oz)",
      "Colocar patty de carne 10:1",
      "Cerrar con el crown (pan superior)",
    ],
    tipEn: "Ketchup and mustard on heel only. 1 pickle — not 2.",
    tipEs: "Catsup y mostaza solo en el heel. 1 pepinillo — no 2.",
  },

  {
    id: "cheeseburger",
    name: "Cheeseburger",
    nameEs: "Hamburguesa con Queso",
    category: "burgers",
    emoji: "🍔",
    steps: [
      "Place heel on wrapper",
      "Apply ketchup (1/3 oz)",
      "Apply mustard (1/10 oz)",
      "Add 2 pickle slices",
      "Add dehydrated onions (1/4 oz)",
      "Place 10:1 beef patty",
      "Add Cheddar cheese slice on patty",
      "Close with crown",
    ],
    stepsEs: [
      "Colocar el heel en el wrapper",
      "Aplicar catsup (1/3 oz)",
      "Aplicar mostaza (1/10 oz)",
      "Agregar 2 rebanadas de pepinillo",
      "Agregar cebolla deshidratada (1/4 oz)",
      "Colocar patty de carne 10:1",
      "Agregar rebanada de queso Cheddar sobre el patty",
      "Cerrar con el crown",
    ],
    tipEn: "2 pickles (vs 1 in hamburger). Cheese goes ON the patty, not under.",
    tipEs: "2 pepinillos (vs 1 en hamburguesa). El queso va SOBRE el patty, no debajo.",
  },

  {
    id: "double-cheeseburger",
    name: "Double Cheeseburger",
    nameEs: "Doble Cheeseburger",
    category: "burgers",
    emoji: "🍔",
    steps: [
      "Place heel on wrapper",
      "Apply ketchup (1/3 oz)",
      "Apply mustard (1/10 oz)",
      "Add 2 pickle slices",
      "Add dehydrated onions (1/4 oz)",
      "Place first 10:1 beef patty",
      "Add Cheddar cheese on first patty",
      "Place second 10:1 beef patty",
      "Add Cheddar cheese on second patty",
      "Close with crown",
    ],
    stepsEs: [
      "Colocar el heel en el wrapper",
      "Aplicar catsup (1/3 oz)",
      "Aplicar mostaza (1/10 oz)",
      "Agregar 2 rebanadas de pepinillo",
      "Agregar cebolla deshidratada (1/4 oz)",
      "Colocar primer patty de carne 10:1",
      "Agregar queso Cheddar en el primer patty",
      "Colocar segundo patty de carne 10:1",
      "Agregar queso Cheddar en el segundo patty",
      "Cerrar con el crown",
    ],
    tipEn: "2 patties, 2 cheese slices — one cheese per patty.",
    tipEs: "2 patties, 2 rebanadas de queso — un queso por patty.",
  },

  {
    id: "mcdouble",
    name: "McDouble",
    nameEs: "McDouble",
    category: "burgers",
    emoji: "🍔",
    steps: [
      "Place heel on wrapper",
      "Apply ketchup (1/3 oz)",
      "Apply mustard (1/10 oz)",
      "Add 2 pickle slices",
      "Add dehydrated onions (1/4 oz)",
      "Place first 10:1 beef patty",
      "Add single Cheddar cheese slice (between patties)",
      "Place second 10:1 beef patty",
      "Close with crown",
    ],
    stepsEs: [
      "Colocar el heel en el wrapper",
      "Aplicar catsup (1/3 oz)",
      "Aplicar mostaza (1/10 oz)",
      "Agregar 2 rebanadas de pepinillo",
      "Agregar cebolla deshidratada (1/4 oz)",
      "Colocar primer patty de carne 10:1",
      "Agregar 1 rebanada de queso Cheddar (entre los patties)",
      "Colocar segundo patty de carne 10:1",
      "Cerrar con el crown",
    ],
    tipEn: "McDouble = 2 patties, 1 cheese (between them). Double CB = 2 patties, 2 cheese.",
    tipEs: "McDouble = 2 patties, 1 queso (entre ellos). Doble CB = 2 patties, 2 quesos.",
  },

  {
    id: "big-mac",
    name: "Big Mac",
    nameEs: "Big Mac",
    category: "burgers",
    emoji: "🍔",
    steps: [
      "Place heel, add Big Mac Sauce (1/3 oz)",
      "Add dehydrated onions (1/8 oz) on heel",
      "Add shredded lettuce (1/4 oz)",
      "Add Cheddar cheese on heel",
      "Add 10:1 patty (heel layer)",
      "Place club bun (middle bun)",
      "Add Big Mac Sauce (1/3 oz) on club",
      "Add dehydrated onions (1/8 oz)",
      "Add shredded lettuce (1/4 oz)",
      "Add 2 pickles + 10:1 patty (club layer)",
      "Close with crown",
    ],
    stepsEs: [
      "Colocar heel, agregar Salsa Big Mac (1/3 oz)",
      "Agregar cebolla deshidratada (1/8 oz) en el heel",
      "Agregar lechuga desmenuzada (1/4 oz)",
      "Agregar queso Cheddar en el heel",
      "Agregar patty 10:1 (capa del heel)",
      "Colocar el club bun (pan del medio)",
      "Agregar Salsa Big Mac (1/3 oz) en el club",
      "Agregar cebolla deshidratada (1/8 oz)",
      "Agregar lechuga desmenuzada (1/4 oz)",
      "Agregar 2 pepinillos + patty 10:1 (capa del club)",
      "Cerrar con el crown",
    ],
    tipEn: "Sauce on BOTH heel and club. Cheese only on the heel patty. Pickles only on club layer.",
    tipEs: "Salsa en AMBOS heel y club. Queso solo en el patty del heel. Pepinillos solo en capa del club.",
  },

  {
    id: "quarter-pounder",
    name: "Quarter Pounder with Cheese",
    nameEs: "Cuarto de Libra con Queso",
    category: "burgers",
    emoji: "🍔",
    steps: [
      "Place heel on wrapper",
      "Apply ketchup (1/3 oz)",
      "Apply mustard (1/10 oz)",
      "Add slivered onions (1/4 oz)",
      "Add 2 pickles",
      "Add Cheddar cheese slice on heel",
      "Place 4:1 beef patty (freshly grilled)",
      "Add second Cheddar cheese slice on patty",
      "Close with crown",
    ],
    stepsEs: [
      "Colocar el heel en el wrapper",
      "Aplicar catsup (1/3 oz)",
      "Aplicar mostaza (1/10 oz)",
      "Agregar cebolla en tiras (1/4 oz)",
      "Agregar 2 pepinillos",
      "Agregar rebanada de queso Cheddar en el heel",
      "Colocar patty de carne 4:1 (recién a la plancha)",
      "Agregar segunda rebanada de queso Cheddar sobre el patty",
      "Cerrar con el crown",
    ],
    tipEn: "QPC uses SLIVERED onions (not dehydrated) and TWO cheese slices.",
    tipEs: "El QPC usa cebolla en TIRAS (no deshidratada) y DOS rebanadas de queso.",
  },

  {
    id: "double-qpc",
    name: "Double Quarter Pounder with Cheese",
    nameEs: "Doble Cuarto de Libra con Queso",
    category: "burgers",
    emoji: "🍔",
    steps: [
      "Place heel on wrapper",
      "Apply ketchup (1/3 oz)",
      "Apply mustard (1/10 oz)",
      "Add slivered onions (1/4 oz)",
      "Add 2 pickles",
      "Add Cheddar cheese on heel",
      "Place first 4:1 patty",
      "Add Cheddar cheese on first patty",
      "Place second 4:1 patty",
      "Add Cheddar cheese on second patty",
      "Close with crown",
    ],
    stepsEs: [
      "Colocar el heel en el wrapper",
      "Aplicar catsup (1/3 oz)",
      "Aplicar mostaza (1/10 oz)",
      "Agregar cebolla en tiras (1/4 oz)",
      "Agregar 2 pepinillos",
      "Agregar queso Cheddar en el heel",
      "Colocar primer patty 4:1",
      "Agregar queso Cheddar en el primer patty",
      "Colocar segundo patty 4:1",
      "Agregar queso Cheddar en el segundo patty",
      "Cerrar con el crown",
    ],
    tipEn: "3 cheese slices total: one on heel, one per patty.",
    tipEs: "3 rebanadas de queso en total: una en el heel, una por patty.",
  },

  {
    id: "filet-o-fish",
    name: "Filet-O-Fish",
    nameEs: "Filet-O-Fish",
    category: "burgers",
    emoji: "🐟",
    steps: [
      "Steam bun both halves for 10–15 seconds",
      "Place heel on wrapper",
      "Add tartar sauce (1/3 oz) on heel",
      "Add half-slice American cheese on heel",
      "Place fried fish fillet on cheese",
      "Close with crown",
    ],
    stepsEs: [
      "Vaporizar el pan (ambas mitades) por 10–15 segundos",
      "Colocar el heel en el wrapper",
      "Agregar salsa tártara (1/3 oz) en el heel",
      "Agregar media rebanada de queso americano en el heel",
      "Colocar el filete de pescado frito sobre el queso",
      "Cerrar con el crown",
    ],
    tipEn: "Only HALF a cheese slice. Bun MUST be steamed — never toasted.",
    tipEs: "Solo MEDIA rebanada de queso. El pan DEBE vaporizarse — nunca tostarse.",
  },

  // ─── CHICKEN & FISH ─────────────────────────────────────────────────────────

  {
    id: "mcchicken",
    name: "McChicken",
    nameEs: "McChicken",
    category: "chicken",
    emoji: "🍗",
    steps: [
      "Place heel on wrapper",
      "Apply mayonnaise (1/2 oz) on heel",
      "Add shredded lettuce (1/2 oz)",
      "Place crispy McChicken patty on lettuce",
      "Close with crown",
    ],
    stepsEs: [
      "Colocar el heel en el wrapper",
      "Aplicar mayonesa (1/2 oz) en el heel",
      "Agregar lechuga desmenuzada (1/2 oz)",
      "Colocar el patty McChicken crujiente sobre la lechuga",
      "Cerrar con el crown",
    ],
    tipEn: "Mayo on heel only — no sauce on crown.",
    tipEs: "Mayo solo en el heel — sin salsa en el crown.",
  },

  {
    id: "crispy-chicken",
    name: "Crispy Chicken Sandwich",
    nameEs: "Sándwich de Pollo Crujiente",
    category: "chicken",
    emoji: "🍗",
    steps: [
      "Toast potato roll — both halves",
      "Apply mayo (1/2 oz) on crown",
      "Add 2 crinkle-cut pickle slices on heel",
      "Place crispy chicken fillet on heel",
      "Close with crown mayo-side down",
    ],
    stepsEs: [
      "Tostar el pan de papa — ambas mitades",
      "Aplicar mayo (1/2 oz) en el crown",
      "Agregar 2 rebanadas de pepinillo corrugado en el heel",
      "Colocar el filete de pollo crujiente en el heel",
      "Cerrar con el crown (lado de mayo hacia abajo)",
    ],
    tipEn: "Mayo on CROWN, pickles on HEEL — opposite of burgers.",
    tipEs: "Mayo en el CROWN, pepinillos en el HEEL — opuesto a las burgers.",
  },

  {
    id: "spicy-crispy-chicken",
    name: "Spicy Crispy Chicken Sandwich",
    nameEs: "Sándwich de Pollo Picante",
    category: "chicken",
    emoji: "🌶️",
    steps: [
      "Toast potato roll — both halves",
      "Apply Spicy Pepper Sauce (1/2 oz) on crown",
      "Add 2 crinkle-cut pickle slices on heel",
      "Place spicy crispy chicken fillet on heel",
      "Close with crown sauce-side down",
    ],
    stepsEs: [
      "Tostar el pan de papa — ambas mitades",
      "Aplicar Salsa Pimienta Picante (1/2 oz) en el crown",
      "Agregar 2 rebanadas de pepinillo corrugado en el heel",
      "Colocar el filete de pollo picante crujiente en el heel",
      "Cerrar con el crown (lado de salsa hacia abajo)",
    ],
    tipEn: "Identical to Crispy Chicken — only Spicy Pepper Sauce replaces mayo.",
    tipEs: "Idéntico al de Pollo Crujiente — solo la Salsa Pimienta Picante reemplaza la mayo.",
  },

  {
    id: "mcnuggets",
    name: "Chicken McNuggets",
    nameEs: "McNuggets de Pollo",
    category: "chicken",
    emoji: "🍗",
    steps: [
      "Drop frozen nuggets in oil at 335°F / 168°C",
      "Fry 2:50 – 3:10 min until golden",
      "Lift basket and drain for 10 seconds",
      "Transfer to nugget holder / tray",
      "Verify hold time — max 20 min, discard after",
      "Place in box with sauce on side",
    ],
    stepsEs: [
      "Sumergir nuggets congelados en aceite a 335°F / 168°C",
      "Freír 2:50 – 3:10 min hasta dorar",
      "Levantar canasta y drenar por 10 segundos",
      "Transferir al soporte de nuggets / bandeja",
      "Verificar tiempo de hold — máximo 20 min, desechar después",
      "Colocar en caja con salsa al lado",
    ],
    tipEn: "Hold ≤ 20 min — both texture and food safety degrade after.",
    tipEs: "Hold ≤ 20 min — tanto la textura como la seguridad alimentaria se degradan después.",
  },

  // ─── McCAFÉ ─────────────────────────────────────────────────────────────────

  {
    id: "hot-latte",
    name: "Hot Latte",
    nameEs: "Latte Caliente",
    category: "mccafe",
    emoji: "☕",
    steps: [
      "Pull 2 espresso shots into cup",
      "Steam milk to 150–165°F — thin microfoam",
      "Pour steamed milk over espresso",
      "Add thin foam layer on top",
      "Secure lid — serve immediately",
    ],
    stepsEs: [
      "Preparar 2 shots de espresso en la taza",
      "Vaporizar leche a 150–165°F — microespuma fina",
      "Verter leche vaporizada sobre el espresso",
      "Agregar capa fina de espuma encima",
      "Asegurar la tapa — servir inmediatamente",
    ],
    tipEn: "Latte = mostly milk with just a thin foam cap. More milk than cappuccino.",
    tipEs: "Latte = principalmente leche con solo una capa fina de espuma. Más leche que cappuccino.",
  },

  {
    id: "iced-latte",
    name: "Iced Latte",
    nameEs: "Latte Frío",
    category: "mccafe",
    emoji: "🥛",
    steps: [
      "Fill cup with ice to the fill line",
      "Pour cold milk over ice (3/4 full)",
      "Pull 2 espresso shots over milk",
      "Add flavor syrup if requested",
      "Secure lid and add straw",
    ],
    stepsEs: [
      "Llenar la taza con hielo hasta la línea",
      "Verter leche fría sobre el hielo (3/4 lleno)",
      "Preparar 2 shots de espresso sobre la leche",
      "Agregar jarabe de sabor si se solicita",
      "Asegurar la tapa y agregar popote",
    ],
    tipEn: "Espresso always LAST in iced drinks — poured over cold milk.",
    tipEs: "El espresso siempre AL ÚLTIMO en bebidas frías — vertido sobre la leche fría.",
  },

  {
    id: "cappuccino",
    name: "Cappuccino",
    nameEs: "Cappuccino",
    category: "mccafe",
    emoji: "☕",
    steps: [
      "Pull 2 espresso shots into cup",
      "Steam milk to 150–165°F — dense foam, 1:1:1 ratio",
      "Pour equal part steamed milk over espresso",
      "Spoon thick foam on top to fill cup",
      "Optional: dust with cocoa powder",
      "Secure lid",
    ],
    stepsEs: [
      "Preparar 2 shots de espresso en la taza",
      "Vaporizar leche a 150–165°F — espuma densa, relación 1:1:1",
      "Verter parte igual de leche vaporizada sobre el espresso",
      "Verter con cuchara espuma gruesa encima para llenar",
      "Opcional: espolvorear cacao en polvo",
      "Asegurar la tapa",
    ],
    tipEn: "Cappuccino = 1/3 espresso, 1/3 milk, 1/3 thick foam. Much more foam than a latte.",
    tipEs: "Cappuccino = 1/3 espresso, 1/3 leche, 1/3 espuma gruesa. Mucha más espuma que un latte.",
  },

  {
    id: "hot-caramel-macchiato",
    name: "Hot Caramel Macchiato",
    nameEs: "Caramel Macchiato Caliente",
    category: "mccafe",
    emoji: "☕",
    steps: [
      "Add vanilla syrup to cup (2 pumps medium, 3 pumps large)",
      "Steam milk to 150–165°F",
      "Pour steamed milk into cup",
      "Pull 2 espresso shots over milk — marking the foam",
      "Drizzle caramel sauce in crosshatch pattern on top",
      "Secure lid",
    ],
    stepsEs: [
      "Agregar jarabe de vainilla a la taza (2 pumps mediano, 3 pumps grande)",
      "Vaporizar leche a 150–165°F",
      "Verter leche vaporizada en la taza",
      "Preparar 2 shots de espresso sobre la leche — marcando la espuma",
      "Rociar salsa de caramelo en patrón de cuadrícula encima",
      "Asegurar la tapa",
    ],
    tipEn: "Milk FIRST, espresso on TOP (the 'mark'). Never mix after building.",
    tipEs: "Leche PRIMERO, espresso ENCIMA (la 'marca'). Nunca mezclar después de armar.",
  },

  {
    id: "iced-caramel-macchiato",
    name: "Iced Caramel Macchiato",
    nameEs: "Caramel Macchiato Frío",
    category: "mccafe",
    emoji: "🍮",
    steps: [
      "Add vanilla syrup to cup",
      "Fill cup with ice",
      "Pour cold milk over ice",
      "Pull 2 espresso shots — pour over milk",
      "Drizzle caramel sauce crosshatch on top",
      "Secure dome lid and add straw",
    ],
    stepsEs: [
      "Agregar jarabe de vainilla a la taza",
      "Llenar la taza con hielo",
      "Verter leche fría sobre el hielo",
      "Preparar 2 shots de espresso — verter sobre la leche",
      "Rociar salsa de caramelo en cuadrícula encima",
      "Asegurar tapa domo y agregar popote",
    ],
    tipEn: "Caramel drizzle always on TOP — never stir before serving.",
    tipEs: "El caramelo siempre encima — nunca revolver antes de servir.",
  },

  {
    id: "caramel-frappe",
    name: "Caramel Frappé",
    nameEs: "Frappé de Caramelo",
    category: "mccafe",
    emoji: "🧋",
    steps: [
      "Fill blender with ice to the line",
      "Add frappé base (5 pumps medium)",
      "Add caramel syrup (3 pumps)",
      "Pull 2 espresso shots into blender",
      "Blend until smooth — 15–20 seconds",
      "Pour into cup",
      "Top with whipped cream",
      "Drizzle caramel sauce on whipped cream",
      "Secure dome lid and add straw",
    ],
    stepsEs: [
      "Llenar el blender con hielo hasta la línea",
      "Agregar base de frappé (5 pumps mediano)",
      "Agregar jarabe de caramelo (3 pumps)",
      "Preparar 2 shots de espresso en el blender",
      "Licuar hasta suavizar — 15–20 segundos",
      "Verter en el vaso",
      "Agregar crema batida encima",
      "Rociar salsa de caramelo sobre la crema batida",
      "Asegurar tapa domo y agregar popote",
    ],
    tipEn: "Espresso goes IN the blender — Frappé is fully blended, unlike macchiato.",
    tipEs: "El espresso va DENTRO del blender — el Frappé se licúa completamente, a diferencia del macchiato.",
  },

  {
    id: "mocha-frappe",
    name: "Mocha Frappé",
    nameEs: "Frappé de Moka",
    category: "mccafe",
    emoji: "🧋",
    steps: [
      "Fill blender with ice to the line",
      "Add frappé base (5 pumps medium)",
      "Add mocha syrup (3 pumps)",
      "Pull 2 espresso shots into blender",
      "Blend until smooth — 15–20 seconds",
      "Pour into cup",
      "Top with whipped cream",
      "Drizzle chocolate sauce on whipped cream",
      "Secure dome lid and add straw",
    ],
    stepsEs: [
      "Llenar el blender con hielo hasta la línea",
      "Agregar base de frappé (5 pumps mediano)",
      "Agregar jarabe de moka (3 pumps)",
      "Preparar 2 shots de espresso en el blender",
      "Licuar hasta suavizar — 15–20 segundos",
      "Verter en el vaso",
      "Agregar crema batida encima",
      "Rociar salsa de chocolate sobre la crema batida",
      "Asegurar tapa domo y agregar popote",
    ],
    tipEn: "Mocha uses mocha syrup + chocolate drizzle. Caramel uses caramel syrup + caramel drizzle.",
    tipEs: "Moka usa jarabe de moka + chocolate. Caramelo usa jarabe de caramelo + caramelo.",
  },

  {
    id: "iced-coffee",
    name: "Iced Coffee",
    nameEs: "Café Frío",
    category: "mccafe",
    emoji: "🥤",
    steps: [
      "Fill cup with ice",
      "Pour brewed McCafé coffee over ice",
      "Add cream if requested",
      "Add flavor syrup (caramel / vanilla / hazelnut)",
      "Secure lid and add straw",
    ],
    stepsEs: [
      "Llenar el vaso con hielo",
      "Verter café McCafé preparado sobre el hielo",
      "Agregar crema si se solicita",
      "Agregar jarabe de sabor (caramelo / vainilla / avellana)",
      "Asegurar la tapa y agregar popote",
    ],
    tipEn: "Iced Coffee uses BREWED coffee (not espresso shots) — pre-chilled.",
    tipEs: "El Café Frío usa café PREPARADO (no shots de espresso) — pre-enfriado.",
  },

  {
    id: "hot-chocolate",
    name: "Hot Chocolate",
    nameEs: "Chocolate Caliente",
    category: "mccafe",
    emoji: "🍫",
    steps: [
      "Add chocolate syrup to cup (3 pumps medium)",
      "Steam milk to 150–165°F",
      "Pour steamed milk over chocolate syrup and stir",
      "Add whipped cream on top",
      "Drizzle chocolate sauce on cream",
      "Secure lid",
    ],
    stepsEs: [
      "Agregar jarabe de chocolate a la taza (3 pumps mediano)",
      "Vaporizar leche a 150–165°F",
      "Verter leche vaporizada sobre el jarabe de chocolate y mezclar",
      "Agregar crema batida encima",
      "Rociar salsa de chocolate sobre la crema",
      "Asegurar la tapa",
    ],
    tipEn: "Stir after adding milk to fully dissolve the chocolate syrup.",
    tipEs: "Mezclar después de agregar la leche para disolver completamente el jarabe de chocolate.",
  },

  // ─── BEVERAGES ───────────────────────────────────────────────────────────────

  {
    id: "soft-drink",
    name: "Fountain Soft Drink",
    nameEs: "Refresco de Fuente",
    category: "beverages",
    emoji: "🥤",
    steps: [
      "Select correct cup size",
      "Fill cup with ice to the fill line",
      "Dispense beverage — leave 1/2 inch headspace",
      "Press lid on firmly",
      "Insert straw through lid",
    ],
    stepsEs: [
      "Seleccionar el tamaño correcto del vaso",
      "Llenar el vaso con hielo hasta la línea",
      "Dispensar la bebida — dejar 1/2 pulgada de espacio",
      "Presionar la tapa firmemente",
      "Insertar el popote a través de la tapa",
    ],
    tipEn: "Ice FIRST, then beverage. Never reverse the order.",
    tipEs: "Hielo PRIMERO, luego la bebida. Nunca invertir el orden.",
  },

  {
    id: "milkshake",
    name: "Milkshake",
    nameEs: "Malteada",
    category: "beverages",
    emoji: "🥛",
    steps: [
      "Place cup under soft-serve machine",
      "Dispense soft serve to fill line",
      "Add flavor syrup (chocolate / vanilla / strawberry)",
      "Blend until smooth and creamy",
      "Top with whipped cream",
      "Secure dome lid and add straw",
    ],
    stepsEs: [
      "Colocar el vaso bajo la máquina de soft serve",
      "Dispensar soft serve hasta la línea de llenado",
      "Agregar jarabe de sabor (chocolate / vainilla / fresa)",
      "Licuar hasta suavizar y cremoso",
      "Agregar crema batida encima",
      "Asegurar tapa domo y agregar popote",
    ],
    tipEn: "Shake temp should be 18–20°F — too warm and it won't hold shape.",
    tipEs: "Temperatura de la malteada: 18–20°F — muy caliente y no mantiene la forma.",
  },

  {
    id: "mcflurry-oreo",
    name: "McFlurry Oreo",
    nameEs: "McFlurry Oreo",
    category: "beverages",
    emoji: "🍦",
    steps: [
      "Place McFlurry cup under soft-serve",
      "Fill soft serve to the fill line",
      "Add Oreo cookie crumbles on top",
      "Insert McFlurry mixer spoon",
      "Mix until evenly combined — 8–10 rotations",
      "Flatten top and remove mixer",
      "Secure McFlurry lid",
    ],
    stepsEs: [
      "Colocar el vaso de McFlurry bajo el soft serve",
      "Llenar el soft serve hasta la línea",
      "Agregar trozos de galleta Oreo encima",
      "Insertar la cuchara mezcladora de McFlurry",
      "Mezclar hasta combinar uniformemente — 8–10 rotaciones",
      "Aplanar la superficie y retirar la mezcladora",
      "Asegurar la tapa de McFlurry",
    ],
    tipEn: "Mix until Oreo pieces are evenly distributed — no clumps at bottom.",
    tipEs: "Mezclar hasta que los Oreos estén distribuidos uniformemente — sin grumos en el fondo.",
  },

  {
    id: "mcflurry-mm",
    name: "McFlurry M&M's",
    nameEs: "McFlurry M&M's",
    category: "beverages",
    emoji: "🍦",
    steps: [
      "Place McFlurry cup under soft-serve",
      "Fill soft serve to the fill line",
      "Add M&M's candy pieces on top",
      "Insert McFlurry mixer spoon",
      "Mix until evenly combined — 8–10 rotations",
      "Flatten top and remove mixer",
      "Secure McFlurry lid",
    ],
    stepsEs: [
      "Colocar el vaso de McFlurry bajo el soft serve",
      "Llenar el soft serve hasta la línea",
      "Agregar piezas de M&M's encima",
      "Insertar la cuchara mezcladora de McFlurry",
      "Mezclar hasta combinar uniformemente — 8–10 rotaciones",
      "Aplanar la superficie y retirar la mezcladora",
      "Asegurar la tapa de McFlurry",
    ],
    tipEn: "Identical process to Oreo McFlurry — only the mix-in changes.",
    tipEs: "Proceso idéntico al McFlurry Oreo — solo cambia el ingrediente.",
  },

  // ─── SIDES ───────────────────────────────────────────────────────────────────

  {
    id: "fries",
    name: "World Famous Fries",
    nameEs: "Papas a la Francesa",
    category: "sides",
    emoji: "🍟",
    steps: [
      "Drop frozen fries in oil at 335°F / 168°C",
      "Fry 3:00 – 3:30 min (regular / medium)",
      "Lift basket and drain for 10–15 seconds",
      "Transfer to fry station dump chute",
      "Salt immediately while hot",
      "Fill container to fill line — no overflow",
      "Hold max 7 min — discard after",
    ],
    stepsEs: [
      "Sumergir papas congeladas en aceite a 335°F / 168°C",
      "Freír 3:00 – 3:30 min (regular / mediano)",
      "Levantar canasta y drenar 10–15 segundos",
      "Transferir a la tolva de la estación de papas",
      "Salar inmediatamente mientras están calientes",
      "Llenar el contenedor hasta la línea — sin desbordamiento",
      "Hold máximo 7 min — desechar después",
    ],
    tipEn: "Salt AFTER draining at dump station — never over the fryer. Hold ≤ 7 min.",
    tipEs: "Salar DESPUÉS de drenar en la estación — nunca sobre la freidora. Hold ≤ 7 min.",
  },

  {
    id: "apple-slices",
    name: "Apple Slices",
    nameEs: "Rebanadas de Manzana",
    category: "sides",
    emoji: "🍎",
    steps: [
      "Retrieve pre-cut apple slices bag from cooler",
      "Check best-by date on package",
      "Portion into serving bag",
      "Seal serving bag",
    ],
    stepsEs: [
      "Obtener bolsa de rebanadas pre-cortadas del refrigerador",
      "Verificar fecha de vencimiento en el empaque",
      "Porcionar en la bolsa de servicio",
      "Sellar la bolsa de servicio",
    ],
    tipEn: "Always verify the date — pre-cut apples have a short shelf life.",
    tipEs: "Siempre verificar la fecha — las manzanas pre-cortadas tienen vida corta.",
  },

  {
    id: "side-salad",
    name: "Side Salad",
    nameEs: "Ensalada",
    category: "sides",
    emoji: "🥗",
    steps: [
      "Retrieve salad bowl from cooler",
      "Add romaine / iceberg lettuce mix",
      "Add grape tomatoes (3–4 pieces)",
      "Add shredded carrots",
      "Add cucumber slices",
      "Place lid on salad bowl",
      "Add dressing packet and fork on the side",
    ],
    stepsEs: [
      "Obtener el tazón de ensalada del refrigerador",
      "Agregar mezcla de lechuga romana / iceberg",
      "Agregar tomates uva (3–4 piezas)",
      "Agregar zanahorias ralladas",
      "Agregar rebanadas de pepino",
      "Colocar la tapa en el tazón",
      "Agregar paquete de aderezo y tenedor al lado",
    ],
    tipEn: "Dressing always on the SIDE — never pre-dressed.",
    tipEs: "El aderezo siempre APARTE — nunca pre-aderezado.",
  },
];
